ovh/the-bastion

- doc/sphinx/installation/basic.rst
Signed-off-by: Germain Carré <git@germain.sh>
> Fixing ssh_config path in documentation

- bin/plugin/admin/adminSudo.json
- lib/perl/OVH/Bastion/interactive.inc
> enh: adminSudo: better autocompletion rules

- lib/perl/OVH/Bastion/allowkeeper.inc
- tests/functional/launch_tests_on_instance.sh
> fix: Allow dot in group name as it is allowed in account

- etc/bastion/bastion.conf.dist
Fix duplicate MFAPasswordMaxDays
Fixes #71
> Fix missing MFAPasswordWarnDays in bastion.conf.dist

- lib/perl/OVH/Bastion/Plugin/groupSetRole.pm
- tests/functional/tests.d/350-groups.sh
Adding a guest access to a member of a group is now denied, to avoid having
dangling guest accesses when their membership is revoked. In effect, they
could no longer access the group servers, even as guest, because they no longer
had access to the group key, but their previous guest accesses were still
visible in groupListGuestAccesses, causing possible confusion.
We now also revoke all guest accesses of an account to a group, if any,
when it's being set as a member of this group, so that when/if the account
membership is revoked, we don't end up with the same ghost guest accesses as above.
> fix: guests: get rid of ghost guest accesses in corner cases

- bin/helper/osh-accountDelete
- bin/sudogen/generate-sudoers.sh
> fix: sudogen: don't check for account/groups validity when deleting

- bin/helper/osh-accountDelete
Relates to #88 (found typo)
Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>
> fix: osh-accountDelete: fix typo

- bin/plugin/open/groupList
- lib/perl/OVH/Bastion.pm
- lib/perl/OVH/Bastion/allowkeeper.inc
- tests/functional/launch_tests_on_instance.sh
On bastions with thousands of group, the speedup is ~x10
> enh: groupList: use cache to speedup calls

- lib/perl/OVH/Bastion/configuration.inc
- tests/functional/tests.d/305-admin-superowner.sh
> fix: admins no longer inherited superowner powers

- lib/perl/OVH/Bastion/interactive.inc
- tests/functional/tests.d/340-selfaccesses.sh
Signed-off-by: Stéphane Lesimple <stephane.lesimple+bastion@ovhcloud.com>
> fix: interactive: omit inactivity msg warning when set to 0 seconds

- lib/perl/OVH/Bastion/log.inc
Signed-off-by: Stéphane Lesimple <stephane.lesimple+bastion@ovhcloud.com>
> chore: more readable version of sql statements

- .github/workflows/documentation.yml
- bin/shell/osh.pl
- lib/perl/OVH/Bastion.pm
> feat: transmit PIV enforcement status to remote realms

- bin/shell/connect.pl
- bin/shell/osh.pl
- tests/functional/launch_tests_on_instance.sh
- tests/functional/tests.d/900-strict-checking.sh
> fix: strict check failure was no longer detected to print a help message

- bin/admin/setup-encryption.sh
> enh: setup-encryption.sh: check that luks-config.sh exists

- bin/admin/setup-gpg.sh
> enh: setup-gpg.sh: clarify the use of ^D with --import

- .github/workflows/freebsd.yml
- README.md
- bin/admin/install
- bin/plugin/restricted/groupCreate
- tests/functional/tests.d/350-groups.sh
> fix: groupCreate: deny groups starting with 'key'

- bin/plugin/open/help
groupAddGuestAccess groupDelGuestAccess are present twice in help
> Remove duplicate groupAddGuestAccess groupDelGuestAccess

- bin/admin/setup-first-admin-account.sh
> fix: setup-first-admin-account.sh: support to add several admins

- bin/plugin/open/clush
- doc/sphinx/plugins/open/clush.rst
- lib/perl/OVH/Bastion/Plugin.pm
> doc: clush: document --user and --port

- lib/perl/OVH/Bastion/allowkeeper.inc
Relates to #220 (found typo)
Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>
> doc: allowkeeper: fix typo

- .github/workflows/tests.yml
- README.md
- bin/admin/check-ssh-hardening.pl
- bin/admin/install
- bin/admin/packages-check.sh
- doc/sphinx/installation/basic.rst
- docker/Dockerfile.centos8
- docker/Dockerfile.rockylinux8
- etc/ssh/ssh_config.default
- etc/ssh/sshd_config.debian7
- etc/ssh/sshd_config.debian8
- etc/ssh/sshd_config.debian9
- etc/ssh/sshd_config.default
- tests/functional/tests.d/325-accountinfo.sh
add:
- Debian 11
- RockyLinux 8
remove:
- OpenSUSE Leap 15.2
- Old minor versions of CentOS 7.x
- Old minor versions of CentOS 8.x
> feat: add new OSes and deprecate old ones

- bin/helper/osh-accountCreate
Relates to #225 (found typo)
Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>
> fix: osh-accountCreate: fix typo

- bin/admin/install
- bin/helper/osh-accountCreate
- bin/plugin/restricted/accountCreate
- lib/perl/OVH/Bastion/ssh.inc
Regardless of the bastion config about the ingressKeysFrom configuration
> fix: install: ensure that the healthcheck user can always connect from 127.0.0.1

- bin/dev/perl-check.sh
- bin/dev/perl-use-all.sh
Parallelize checks and make the Perl module checking in O(1) instead of O(n)
> enh: tests: faster perl-check script

- bin/plugin/open/scp
This CVE will not be fixed by scp authors, and as far as The Bastion is concerned, this can't be achieved by anybody that doesn't already have shell access to the remote server in addition to the scp rights, but let's still block it for good measure.
> fix: basic mitigation for scp's CVE-2020-15778

- bin/helper/osh-accountFreezeToggle
- bin/plugin/restricted/accountFreeze
- bin/plugin/restricted/accountInfo
- bin/plugin/restricted/accountList
- bin/plugin/restricted/accountUnfreeze
- bin/shell/osh.pl
- doc/sphinx/plugins/restricted/accountList.rst
- doc/sphinx/plugins/restricted/index.rst
- etc/sudoers.d/osh-plugin-accountFreezeToggle
- lib/perl/OVH/Bastion.pm
- tests/functional/tests.d/325-accountinfo.sh
feat: add accountFreeze/accountUnfreeze
enh: accountInfo: add --no-password-info and --no-output
enh: osh.pl: add the account name on each error message
> add accountFreeze / accountUnfreeze

- bin/helper/osh-groupCreate
- tests/functional/tests.d/350-groups.sh
> fix: typo in a func name in an error code path

- bin/helper/osh-accountCreate
- bin/helper/osh-groupCreate
- lib/perl/OVH/Bastion/Helper.pm
> fix: race condition when two parallel account creations used --uid-auto

- bin/helper/osh-groupAddServer
- bin/plugin/group-aclkeeper/groupAddServer
- bin/plugin/restricted/accountAddPersonalAccess
- bin/plugin/restricted/selfAddPersonalAccess
- bin/shell/osh.pl
- lib/perl/OVH/Bastion/allowdeny.inc
- tests/functional/tests.d/350-groups.sh
> fix: --force-key wasn't working for groups

- bin/plugin/open/clush
- bin/plugin/open/ping
- bin/plugin/open/selfMFASetupPassword
- bin/shell/connect.pl
- bin/shell/osh.pl
- lib/perl/OVH/Bastion/Plugin.pm
> enh: plugins: better signal handling to avoid dangling children processes

- bin/cron/osh-lingering-sessions-reaper.sh
> fix: osh-lingering-session-reaper.sh: make 'ps' usage FreeBSD compatible
