ovh/the-bastion

bin/admin/packages-check.sh
This enables direct printing of the qrcode on the terminal for TOTP enrollment
=> enh: packages-check.sh: add qrencode-libs for rhel/centos

bin/plugin/admin/adminSudo
add expects_stdin to the execute call so an admin will be able to replay session from another account
=> allow adminSudo plugin to read from stdin

bin/cron/osh-encrypt-rsync.pl
As stated in the .dist example, logfile parameter is optional.
Remove it from mandatory keywork found in the configuration
=> osh-encrypt-rsync: Remove logfile as mandatory parameter

etc/bastion/bastion.conf.dist
See [configuration.inc:192](https://github.com/ovh/the-bastion/blob/master/lib/perl/OVH/Bastion/configuration.inc#L192):
```perl
if (!grep { $C->{'accountMFAPolicy'} eq $_ } qw{ disabled enabled password-required totp-required any-required }) {
$C->{'accountMFAPolicy'} = 'enabled';
}
```
=> Fixed accountMFAPolicy wrong options values

doc/sphinx/installation/upgrading.rst, etc/bastion/bastion.conf.dist, lib/perl/OVH/Bastion/configuration.inc
=> Fixed wrong default values in bastion.conf comments

bin/plugin/group-aclkeeper/groupDelServer
Error messages were copypasta of groupAddServer.
Signed-off-by: Pierre Kuhner <pierre.kuhner@ovhcloud.com>
=> fix: confusing error messages in groupDelServer

bin/cron/osh-lingering-sessions-reaper.sh
which could terminate the script early with a
`osh-lingering-sessions-reaper.sh[12345]: ERROR: Unexpected termination!`
syslog message
=> fix: osh-lingering-sessions-reaper.sh: tocttou on kill

doc/sphinx/administration/bastion_conf.rst, etc/bastion/bastion.conf.dist, lib/perl/OVH/Bastion/configuration.inc
Before, an inconsistency in the configuration settings of the warnBefore(Lock|Kill)Seconds
and idle(Lock|Kill)Timeout could break any new connection (ttyrec refuses to launch).
Now we detect this case properly, and fallback to a sane setting for
warnBefore(Lock|Kill)Seconds (zero) if those were set without enabling the corresponding
idle(Lock|Kill)Timeout setting. We also log an error to syslog when it happens,
so that the sysadmin can fix their configuration.
Added hints about how these configuration options work together in the bastion.conf.dist file.
Fixes #125
=> enh: config: detect warnBefore/idleTimeout misconfiguration

.github/workflows/freebsd.yml, bin/admin/install, bin/admin/osh-sync-watcher.sh, bin/sudogen/generate-sudoers.sh, lib/shell/functions.inc
This fixes a race condition in sudo where it would log a log of
error messages to syslog if used while we're running the install
script: files around sudoers.d/ are then moved around, and it'll
yell for each file it previously listed if the file no longer
exists when it tries to stat() it. It also deprecates the --no-wait
flag of the install script, as now the sudoers.d/ directory will
always have integrity at all times.
Signed-off-by: Stéphane Lesimple <stephane.lesimple+bastion@ovhcloud.com>
=> enh: install: use in-place overwrite for sudoers files

bin/plugin/restricted/accountInfo, lib/perl/OVH/Bastion/interactive.inc
This occurred since `v3.01.99-rc1` when requesting an `accountInfo`
of an account without an `ingress_piv_policy` set.
`Use of uninitialized value  in concatenation (.) or string at /usr/share/perl/5.28/Term/ANSIColor.pm line 510.
at /opt/bastion/bin/plugin/restricted/../../../lib/perl/OVH/Bastion.pm line 41.
OVH::Bastion::__ANON__("Use of uninitialized value \ in concatenation (.) or st"...) called at /usr/share/perl/5.28/Term/ANSIColor.pm line 510
Term::ANSIColor::colored(undef, "green") called at /opt/bastion/bin/plugin/restricted/accountInfo line 178`
=> fix: accountInfo: get rid of 2 warn()

bin/plugin/open/scp, tests/functional/tests.d/340-selfaccesses.sh
The following warn would happen if the scp wrapper was called with an invalid hostname:
```
Use of uninitialized value  in bitwise and (&) at /usr/share/perl5/Net/Netmask.pm line 699.
at /opt/bastion/bin/plugin/open/../../../lib/perl/OVH/Bastion.pm line 41.
OVH::Bastion::__ANON__("Use of uninitialized value \ in bitwise and (&) at /usr/shar"...) called at /usr/share/perl5/Net/Netmask.pm line 697
Net::Netmask::match(Net::Netmask=HASH(0x55b1d5f11860), undef) called at /opt/bastion/lib/perl/OVH/Bastion/allowdeny.inc line 214
OVH::Bastion::is_access_way_granted("port", 22, "exactUserMatch", 1, "ipfrom", "X.X.X.X", "ip", undef, ...) called at /opt/bastion/lib/perl/OVH/Bastion/allowdeny.inc line 688
OVH::Bastion::is_access_granted(\"account\", \"johndoe\", \"user\", \"!scpupload\", \"ipfrom\", …
```
=> fix: scp: abort early if host is not found to avoid a warn()

bin/plugin/open/help
=> fix: osh-help: put groupDelEgressKey in the proper category

bin/admin/unlock-home.sh
=> Fix typo in unlock-home.sh

bin/helper/osh-accountModify, bin/plugin/restricted/accountModify, bin/plugin/restricted/accountModify.json, doc/sphinx/plugins/restricted/accountModify.rst, tests/functional/tests.d/330-selfkeys.sh
Hi,
Currently, the parameter `--egress-strict-host-key-checking` of `accountModify` plugin only supports `yes`, `no`, `ask`, `default`, `bypass` and then references `man ssh_config` for additional informations.
One of the keyword is missing, it is called `accept-new` and is very convenient in our usage with The Bastion and CI/CD. It permits to auto accept new HostKeys but blocks in case of the already auto accepted HostKey is changed, to avoid MitM.
It something between `yes` and `no`.
I tested this code in our The Bastion test cluster which is running `v3.03.01`.
Regards,
DCO: Signed-off-by: Jonathan Marsaud <jonathan.marsaud@iguanesolutions.com>
=> accountModify - Add a new `accept-new` POLICY in egress-strict-host-key-checking parameter

bin/helper/osh-groupDelete, bin/plugin/group-owner/groupDestroy, bin/plugin/group-owner/groupDestroy.json, bin/shell/connect.pl, doc/sphinx/plugins/group-owner/index.rst, doc/sphinx/plugins/restricted/groupDelete.rst, etc/sudoers.group.template.d/500-base.sudoers, tests/functional/tests.d/350-groups.sh
This command deletes a group, as `groupDelete` does, but works
for owners so that they can delete their own group.
`groupDelete` remains as a restricted command, able to delete any group.
=> feat: add groupDestroy command for owners

bin/proxy/osh-http-proxy-daemon, bin/proxy/osh-http-proxy-worker, etc/bastion/osh-http-proxy.conf.dist, lib/perl/OVH/Bastion/ProxyHTTP.pm
Added the `log_request_response` and `log_request_response_max_size`
options to osh-http-proxy.conf.
By default, requests are logged, including their body, up to a size
of 64K per request response. Before, there was no size limit to the
logged body response.
=> enh: httpproxy: add options to fine-tune logging

bin/plugin/open/info, tests/functional/tests.d/320-base.sh
For auditing purposes, get admin and super owner list in info plugin
Available for auditor role only
=> Feat: Add admin and super owner accounts list in info plugin

bin/helper/osh-accountCreate, lib/perl/OVH/Bastion/allowkeeper.inc
This happened when a free UID was found, along with a corresponding GID,
but the corresponding GID for the ttyrec group of the account was not
available. Now this is checked directly in get_next_available_uid()
=> fix: accountCreate --uid-auto: rare case where a free UID couldn't be found

bin/plugin/restricted/accountInfo, doc/sphinx/plugins/restricted/accountInfo.rst, tests/functional/tests.d/325-accountinfo.sh
Listing groups can be slow on bastions having thousands
of groups, hence this is now disabled by default.
=> enh: accountInfo: add --list-groups

tests/functional/docker/docker_build_and_run_tests.sh, tests/functional/launch_tests_on_instance.sh, tests/functional/tests.d/300-activeness.sh, tests/functional/tests.d/305-admin-superowner.sh, tests/functional/tests.d/310-realm.sh, tests/functional/tests.d/320-base.sh, tests/functional/tests.d/325-accountinfo.sh, tests/functional/tests.d/330-selfkeys.sh, tests/functional/tests.d/340-selfaccesses.sh, tests/functional/tests.d/350-groups.sh, tests/functional/tests.d/360-plugins.sh, tests/functional/tests.d/370-mfa.sh, tests/functional/tests.d/390-mfa-realm.sh, tests/functional/tests.d/400-piv.sh, tests/functional/tests.d/500-http-proxy.sh, tests/functional/tests.d/900-strict-checking.sh
As tests are now split by modules, the section is autodetected
and taken as the module name, hence a test now only needs a name,
instead of a section & a name.
=> chore: remove useless 'section' test info

bin/dev/perlcriticrc, bin/plugin/open/selfMFASetupPassword, bin/plugin/open/selfMFASetupTOTP, bin/shell/osh.pl, doc/sphinx/administration/configuration/bastion_conf.rst, etc/bastion/bastion.conf.dist, lib/perl/OVH/Bastion/configuration.inc, lib/perl/OVH/Bastion/interactive.inc, tests/functional/tests.d/370-mfa.sh
For bastions using JIT MFA, where MFA can be requested when
attempting to connect through specific groups, or when using
some commands, with respect to MFA being enforced at connection
time directly through the sshd authentication process, one can
now request MFA validation in advance, to workaround problems
in commands such as ``clush``  or ``batch``, and interactive mode.
=> add ``--proactive-mfa`` and mfa/nofa interactive commands

doc/sphinx/administration/configuration/bastion_conf.rst, etc/bastion/bastion.conf.dist
To add a superowner, it is needed to also make part of the `osh-superowner` group (the same way as the admins).
Here is a small documentation add this information.
Signed-off-by: Jean "henyxia" Wasilewski <henyxia@revs0.com>
=> fix: add superowner group requirement

lib/perl/OVH/Bastion/os.inc
Groups that were containing 'lock' or 'retry' in their name
would falsely trigger the /etc/passwd and /etc/group lock
contention detection, due to their presence in the output of
the system command, implying several retries that were not
needed.
=> fix: groupdel: false positive in lock contention detection

bin/helper/osh-accountModifyPersonalAccess, bin/helper/osh-groupAddServer, bin/plugin/group-aclkeeper/groupAddServer, bin/plugin/group-aclkeeper/groupAddServer.json, bin/plugin/restricted/accountAddPersonalAccess, bin/plugin/restricted/accountAddPersonalAccess.json, bin/plugin/restricted/selfAddPersonalAccess, bin/plugin/restricted/selfAddPersonalAccess.json, bin/shell/autologin, bin/shell/osh.pl, doc/sphinx/plugins/group-aclkeeper/groupAddServer.rst, doc/sphinx/plugins/restricted/accountAddPersonalAccess.rst, doc/sphinx/plugins/restricted/selfAddPersonalAccess.rst, lib/perl/OVH/Bastion.pm, lib/perl/OVH/Bastion/allowdeny.inc, lib/perl/OVH/Bastion/allowkeeper.inc, lib/perl/OVH/Bastion/password.inc, tests/functional/tests.d/341-selfaccesses-force-password.sh
This is like --force-key, but for passwords
When this option is set, instead of autologin trying all the passwords until one works, only the one matching the hash is tried
If no password matches the hash then it aborts
This works for both personal accesses and group accesses
=> new access option: --force-password <HASH>, to only try one specific password

bin/cron/osh-encrypt-rsync.pl
This would lead to actually skipping some of the folders,
possibly an oddity of File::Find::find
=> fix: osh-encrypt-rsync.pl: don't add some folders twice

bin/plugin/open/alive, doc/sphinx/plugins/open/alive.rst
Hello,
Small pull-request to fix a typo in the `alive` command.
=> fix: typo in the 'alive' command

doc/sphinx/using/piv.rst
code:: is not a recognized statement for sphinx,
code-blocks, as used on all other pages, is the correct one.
Syntax highlighting with shell does not work for the last two blocks.
Can also be seen on: https://ovh.github.io/the-bastion/using/piv.html all the code blocks are missing
=> fix: doc: use code-blocks:: instead of code::

bin/plugin/open/scp, lib/perl/OVH/Bastion/execute.inc, tests/functional/tests.d/330-selfkeys.sh
Under some specific conditions, the execute() call could get deadlocked with the program it started, both waiting for each other to read or write data. This is easier to reproduce with the `scp` plugin, where the transfer would just stall. Introduce an additional intermediate buffer to avoid this race condition.
=> fix: rare race condition introduced by b7f4909

DESIGN.md, doc/sphinx/faq.rst, doc/sphinx/presentation/principles.rst, doc/sphinx/using/basics/access_management.rst
Actual links are broken, this update now uses blog.ovhcloud.com
=> [Doc] Update ovh.com/blog links

bin/plugin/open/alive, tests/functional/launch_tests_on_instance.sh, tests/functional/tests.d/360-plugins.sh
As ping can return unknown exit codes for unknown cases, just never bail out to avoid taking bad decisions, as we retry each second maximum, there's no DoS risk
=> fix: don't exit with fping host is unreachable

bin/shell/osh.pl, doc/sphinx/administration/configuration/bastion_conf.rst, etc/bastion/bastion.conf.dist, lib/perl/OVH/Bastion.pm, lib/perl/OVH/Bastion/configuration.inc
Commands that generate a lot of stdout output and are M2M workflows, such as rsync, can now be excluded from ttyrec to avoid filling up drives
=> feat: add ttyrecStealthStdoutPattern config

etc/pam.d/sshd.rhel
Due to `pam_tally2.so` not being readily available in RHEL/derivatives (base/EPEL), it was commented out of the `pam.d/sshd` template used for RHEL. However, this change didn't take into account the `pam_succeed_if.so` module skipping a specific number of rules, and commenting out this rule without adjusting the `default=` line caused strange behavior in certain configurations.
I adjusted the `default=` line to account for this and added a verbose comment to the template for future people.
The templates for the other distributions look fine.
`Signed-off-by: Cody Robertson <cody@nerdymuffin.com>`
=> Adjust etc/pam.d/sshd.rhel configuration

docker/devenv/run-tool.sh
Hi,
The documentation of the `docker/devenv/run-tool.sh` state that the run command should be used. But it doesn't exist in code. As I understood it was the same behavior as bash command in code so I added it.
Hope it will be helpful.
=> fix: adding run command in code to match doc

bin/shell/osh.pl, tests/functional/tests.d/350-groups.sh
This option introduce a wait for an open port instead of a simple ping. Sometimes it takes a very long time between the ping and the ssh access.
=> feat: add option to wait for a specific port open

bin/plugin/open/selfPlaySession
We'll try to find the ttyrec file ourselves, given the uniqid. This also enables ttyplaying for osh plugins.
=> enh: selfPlaySession: remove sqliteLog.ttyrecfile dependency

lib/perl/OVH/Bastion.pm, tests/unit/run.pl
Before 932e72e, plugin-scoped stealthStdout was ignored, which was fixed by 932e72e which in turn made ssh ignore the pattern-based egress ssh stealthStdout option.
This fix ensures stealthStdout is honored for both plugins and egress ssh.
=> fix: regression introduced by 932e72e for stealth stdout in ssh

bin/plugin/group-gatekeeper/groupAddGuestAccess, bin/plugin/group-gatekeeper/groupDelGuestAccess, bin/plugin/open/scp, bin/plugin/restricted/accountAddPersonalAccess, bin/plugin/restricted/accountDelPersonalAccess, bin/plugin/restricted/selfAddPersonalAccess, bin/plugin/restricted/selfDelPersonalAccess, doc/sphinx-plugins-override/scp.override.rst, doc/sphinx/installation/upgrading.rst, doc/sphinx/plugins/group-gatekeeper/groupAddGuestAccess.rst, doc/sphinx/plugins/group-gatekeeper/groupDelGuestAccess.rst, doc/sphinx/plugins/open/scp.rst, doc/sphinx/plugins/restricted/accountAddPersonalAccess.rst, doc/sphinx/plugins/restricted/accountDelPersonalAccess.rst, doc/sphinx/plugins/restricted/selfAddPersonalAccess.rst, doc/sphinx/plugins/restricted/selfDelPersonalAccess.rst, doc/sphinx/using/sftp_scp_rsync.rst, lib/perl/OVH/Bastion/Plugin/ACL.pm, tests/functional/tests.d/395-mfa-scp-sftp-rsync.sh
There were an issue with the error message when trying to add a server with `--protocol scpdown` or  `--protocol scpup` (instead of the correct `--protocol scpdownload` or  `--protocol scpupload`) : 
```
The protocol 'scpup' is not supported, expected either scpup, scpdown, sftp or rsync
```
Similarly the documentation was wrong on the correct syntaxe for those kind of calls.
=> Correction of error message and documentation

bin/shell/osh.pl, doc/sphinx/administration/configuration/bastion_conf.rst, doc/sphinx/presentation/features.rst, etc/bastion/bastion.conf.dist, lib/perl/OVH/Bastion/configuration.inc, tests/functional/tests.d/346-testagentforward.sh
This pull request addresses and resolves issue #252 by implementing the capability to enable SSH agent forwarding during an SSH session, with the egress key added to the agent.
The behavior is controlled by the ``sshAddKeysToAgentAllowed`` configuration option in bastion.conf, which is set to ``false`` by default. When this option is explicitly set to ``true``, users can request SSH agent forwarding by including either the ``--forward-agent`` or ``-x`` argument on egress SSH sessions:
```
ssh --forward-agent <username>@<host>  
ssh -x <username>@<host>  
```
This enhancement provides users with greater flexibility while maintaining the secure default settings and addresses the exact scenario described in #252.
Tests have been added in its own file, as I couldn't really find a more …
=> Implement ssh --forward-agent | -x functionality

bin/helper/osh-groupSetServers, tests/functional/tests.d/350-groups.sh
Comment part was parsed but not pushed on group information.
It was missing on osh-groupSetServers part.
=> [fix] Add comment to groupSetServers

bin/admin/setup-encryption.sh
Hi,
Most servers using systemd require a `sytemctl daemon-reload` after making changes to `/etc/fstab` because systemd generates systemd-mounts for all mount points under the hood.
Without the daemon-reload, I'm getting this warning:
```
mount: (hint) your fstab has been modified, but systemd still uses the old version; 
use 'systemctl daemon-reload' to reload.
```
=> fix: execute systemctl daemon-reload after /etc/fstab changes
